#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
//const yargs = require('yargs-parser')
//yargs
const yaml = require('js-yaml')
const { stringify } = require('json5')
const json5 = require('json5')
stringify({a:1,b:2})
files = fs.readdirSync('.')
files
let cat = p => {
return fs.readFileSync(p).toLocaleString()
}
//cat("temp.js")
